export type SupportedCitySeed = {
  seedKey: string;
  name: string;
  countryCode: string;
  timezone: string;
  latitude: number;
  longitude: number;
  airportCode?: string;
  contactEmail?: string;
  contactPhone?: string;
  contactAddress?: string;
  notes?: string;
  sortOrder?: number;
};

/** Curated airport cities — East Africa corridor + Western/Southern Europe hubs. */
export const SUPPORTED_CITIES: SupportedCitySeed[] = [
  // ─── Rwanda ───────────────────────────────────────────────────────────────
  {
    seedKey: 'rw-kigali',
    name: 'Kigali',
    countryCode: 'RW',
    timezone: 'Africa/Kigali',
    latitude: -1.9686,
    longitude: 30.1395,
    airportCode: 'KGL',
    contactEmail: 'logistics@kgl-airport.rw',
    contactPhone: '+250 788 300 100',
    contactAddress: 'Kigali International Airport, KK 15 Rd, Kigali',
    notes: 'Primary Rwanda hub for East Africa routes.',
    sortOrder: 1,
  },

  // ─── Kenya ──────────────────────────────────────────────────────────────────
  {
    seedKey: 'ke-nairobi',
    name: 'Nairobi',
    countryCode: 'KE',
    timezone: 'Africa/Nairobi',
    latitude: -1.3192,
    longitude: 36.9278,
    airportCode: 'NBO',
    contactEmail: 'cargo@kenya-airways.com',
    contactPhone: '+254 20 327 4747',
    contactAddress: 'Jomo Kenyatta International Airport, Nairobi',
    notes: 'Major East Africa aviation hub.',
    sortOrder: 10,
  },
  {
    seedKey: 'ke-mombasa',
    name: 'Mombasa',
    countryCode: 'KE',
    timezone: 'Africa/Nairobi',
    latitude: -4.0348,
    longitude: 39.5942,
    airportCode: 'MBA',
    contactEmail: 'info@kenyaairports.co.ke',
    contactPhone: '+254 41 342 5555',
    contactAddress: 'Moi International Airport, Mombasa',
    sortOrder: 11,
  },
  {
    seedKey: 'ke-kisumu',
    name: 'Kisumu',
    countryCode: 'KE',
    timezone: 'Africa/Nairobi',
    latitude: -0.0917,
    longitude: 34.728,
    airportCode: 'KIS',
    contactEmail: 'info@kenyaairports.co.ke',
    contactPhone: '+254 57 202 3121',
    contactAddress: 'Kisumu International Airport',
    sortOrder: 12,
  },
  {
    seedKey: 'ke-eldoret',
    name: 'Eldoret',
    countryCode: 'KE',
    timezone: 'Africa/Nairobi',
    latitude: 0.4044,
    longitude: 35.2389,
    airportCode: 'EDL',
    contactEmail: 'info@kenyaairports.co.ke',
    contactPhone: '+254 53 206 3100',
    contactAddress: 'Eldoret International Airport',
    sortOrder: 13,
  },

  // ─── Tanzania ───────────────────────────────────────────────────────────────
  {
    seedKey: 'tz-dar-es-salaam',
    name: 'Dar es Salaam',
    countryCode: 'TZ',
    timezone: 'Africa/Dar_es_Salaam',
    latitude: -6.8781,
    longitude: 39.2026,
    airportCode: 'DAR',
    contactEmail: 'info@tanzaniaairports.co.tz',
    contactPhone: '+255 22 284 4320',
    contactAddress: 'Julius Nyerere International Airport, Dar es Salaam',
    sortOrder: 20,
  },
  {
    seedKey: 'tz-zanzibar',
    name: 'Zanzibar',
    countryCode: 'TZ',
    timezone: 'Africa/Dar_es_Salaam',
    latitude: -6.222,
    longitude: 39.2249,
    airportCode: 'ZNZ',
    contactEmail: 'info@tanzaniaairports.co.tz',
    contactPhone: '+255 24 223 3700',
    contactAddress: 'Abeid Amani Karume International Airport, Zanzibar',
    sortOrder: 21,
  },
  {
    seedKey: 'tz-kilimanjaro',
    name: 'Kilimanjaro',
    countryCode: 'TZ',
    timezone: 'Africa/Dar_es_Salaam',
    latitude: -3.4294,
    longitude: 37.0745,
    airportCode: 'JRO',
    contactEmail: 'info@tanzaniaairports.co.tz',
    contactPhone: '+255 27 255 4252',
    contactAddress: 'Kilimanjaro International Airport, Arusha region',
    sortOrder: 22,
  },
  {
    seedKey: 'tz-arusha',
    name: 'Arusha',
    countryCode: 'TZ',
    timezone: 'Africa/Dar_es_Salaam',
    latitude: -3.3869,
    longitude: 36.683,
    airportCode: 'ARK',
    contactEmail: 'info@tanzaniaairports.co.tz',
    contactPhone: '+255 27 250 8000',
    contactAddress: 'Arusha Airport',
    notes: 'Regional airport; international flights often use JRO.',
    sortOrder: 23,
  },

  // ─── Uganda ─────────────────────────────────────────────────────────────────
  {
    seedKey: 'ug-kampala',
    name: 'Kampala',
    countryCode: 'UG',
    timezone: 'Africa/Kampala',
    latitude: 0.3476,
    longitude: 32.5825,
    airportCode: 'EBB',
    contactEmail: 'info@caa.co.ug',
    contactPhone: '+256 312 352 000',
    contactAddress: 'Entebbe International Airport (serves Kampala)',
    notes: 'International flights land at Entebbe (EBB).',
    sortOrder: 30,
  },
  {
    seedKey: 'ug-entebbe',
    name: 'Entebbe',
    countryCode: 'UG',
    timezone: 'Africa/Kampala',
    latitude: 0.0424,
    longitude: 32.4435,
    airportCode: 'EBB',
    contactEmail: 'info@caa.co.ug',
    contactPhone: '+256 312 352 000',
    contactAddress: 'Entebbe International Airport',
    sortOrder: 31,
  },

  // ─── Ethiopia ───────────────────────────────────────────────────────────────
  {
    seedKey: 'et-addis-ababa',
    name: 'Addis Ababa',
    countryCode: 'ET',
    timezone: 'Africa/Addis_Ababa',
    latitude: 8.9779,
    longitude: 38.7993,
    airportCode: 'ADD',
    contactEmail: 'cargo@ethiopianairlines.com',
    contactPhone: '+251 11 665 2222',
    contactAddress: 'Bole International Airport, Addis Ababa',
    notes: 'Major African hub via Ethiopian Airlines.',
    sortOrder: 40,
  },

  // ─── United Kingdom ─────────────────────────────────────────────────────────
  {
    seedKey: 'gb-london',
    name: 'London',
    countryCode: 'GB',
    timezone: 'Europe/London',
    latitude: 51.47,
    longitude: -0.4543,
    airportCode: 'LHR',
    contactEmail: 'cargo@heathrow.com',
    contactPhone: '+44 844 335 1801',
    contactAddress: 'Heathrow Airport, Longford, Hounslow TW6',
    sortOrder: 100,
  },
  {
    seedKey: 'gb-manchester',
    name: 'Manchester',
    countryCode: 'GB',
    timezone: 'Europe/London',
    latitude: 53.3537,
    longitude: -2.275,
    airportCode: 'MAN',
    contactEmail: 'cargo@manchesterairport.co.uk',
    contactPhone: '+44 808 169 7030',
    contactAddress: 'Manchester Airport, M90 1QX',
    sortOrder: 101,
  },
  {
    seedKey: 'gb-birmingham',
    name: 'Birmingham',
    countryCode: 'GB',
    timezone: 'Europe/London',
    latitude: 52.4539,
    longitude: -1.748,
    airportCode: 'BHX',
    contactEmail: 'cargo@birminghamairport.co.uk',
    contactPhone: '+44 871 222 0072',
    contactAddress: 'Birmingham Airport, B26 3QJ',
    sortOrder: 102,
  },
  {
    seedKey: 'gb-edinburgh',
    name: 'Edinburgh',
    countryCode: 'GB',
    timezone: 'Europe/London',
    latitude: 55.95,
    longitude: -3.3725,
    airportCode: 'EDI',
    contactEmail: 'cargo@edinburghairport.com',
    contactPhone: '+44 844 448 8833',
    contactAddress: 'Edinburgh Airport, EH12 9DN',
    sortOrder: 103,
  },

  // ─── France ─────────────────────────────────────────────────────────────────
  {
    seedKey: 'fr-paris',
    name: 'Paris',
    countryCode: 'FR',
    timezone: 'Europe/Paris',
    latitude: 49.0097,
    longitude: 2.5479,
    airportCode: 'CDG',
    contactEmail: 'cargo@adp.fr',
    contactPhone: '+33 1 70 36 39 50',
    contactAddress: 'Charles de Gaulle Airport, 95700 Roissy-en-France',
    sortOrder: 110,
  },
  {
    seedKey: 'fr-lyon',
    name: 'Lyon',
    countryCode: 'FR',
    timezone: 'Europe/Paris',
    latitude: 45.7256,
    longitude: 5.0811,
    airportCode: 'LYS',
    contactEmail: 'cargo@lyonaeroports.com',
    contactPhone: '+33 826 800 826',
    contactAddress: 'Lyon-Saint Exupéry Airport, 69125 Colombier-Saugnieu',
    sortOrder: 111,
  },
  {
    seedKey: 'fr-nice',
    name: 'Nice',
    countryCode: 'FR',
    timezone: 'Europe/Paris',
    latitude: 43.6584,
    longitude: 7.2159,
    airportCode: 'NCE',
    contactEmail: 'cargo@nice.aeroport.fr',
    contactPhone: '+33 4 93 21 30 30',
    contactAddress: 'Nice Côte d\'Azur Airport, 06206 Nice',
    sortOrder: 112,
  },

  // ─── Netherlands ────────────────────────────────────────────────────────────
  {
    seedKey: 'nl-amsterdam',
    name: 'Amsterdam',
    countryCode: 'NL',
    timezone: 'Europe/Amsterdam',
    latitude: 52.3105,
    longitude: 4.7683,
    airportCode: 'AMS',
    contactEmail: 'cargo@schiphol.nl',
    contactPhone: '+31 20 794 0800',
    contactAddress: 'Amsterdam Airport Schiphol, Evert van de Beekstraat 202',
    sortOrder: 120,
  },

  // ─── Germany ────────────────────────────────────────────────────────────────
  {
    seedKey: 'de-frankfurt',
    name: 'Frankfurt',
    countryCode: 'DE',
    timezone: 'Europe/Berlin',
    latitude: 50.0379,
    longitude: 8.5622,
    airportCode: 'FRA',
    contactEmail: 'cargo@fraport.de',
    contactPhone: '+49 69 690 700',
    contactAddress: 'Frankfurt Airport, 60547 Frankfurt am Main',
    sortOrder: 130,
  },
  {
    seedKey: 'de-munich',
    name: 'Munich',
    countryCode: 'DE',
    timezone: 'Europe/Berlin',
    latitude: 48.3537,
    longitude: 11.775,
    airportCode: 'MUC',
    contactEmail: 'cargo@munic-airport.de',
    contactPhone: '+49 89 975 00',
    contactAddress: 'Munich Airport, Nordallee 25, 85356 München-Flughafen',
    sortOrder: 131,
  },
  {
    seedKey: 'de-berlin',
    name: 'Berlin',
    countryCode: 'DE',
    timezone: 'Europe/Berlin',
    latitude: 52.3667,
    longitude: 13.5033,
    airportCode: 'BER',
    contactEmail: 'cargo@berlin-airport.de',
    contactPhone: '+49 30 609 160 910',
    contactAddress: 'Berlin Brandenburg Airport, Melli-Beese-Ring 1',
    sortOrder: 132,
  },
  {
    seedKey: 'de-dusseldorf',
    name: 'Düsseldorf',
    countryCode: 'DE',
    timezone: 'Europe/Berlin',
    latitude: 51.2895,
    longitude: 6.7668,
    airportCode: 'DUS',
    contactEmail: 'cargo@dus.com',
    contactPhone: '+49 211 421 0',
    contactAddress: 'Düsseldorf Airport, Flughafenstraße 120',
    sortOrder: 133,
  },

  // ─── Spain ──────────────────────────────────────────────────────────────────
  {
    seedKey: 'es-madrid',
    name: 'Madrid',
    countryCode: 'ES',
    timezone: 'Europe/Madrid',
    latitude: 40.4983,
    longitude: -3.5676,
    airportCode: 'MAD',
    contactEmail: 'carga@aena.es',
    contactPhone: '+34 913 211 000',
    contactAddress: 'Adolfo Suárez Madrid-Barajas Airport',
    sortOrder: 140,
  },
  {
    seedKey: 'es-barcelona',
    name: 'Barcelona',
    countryCode: 'ES',
    timezone: 'Europe/Madrid',
    latitude: 41.2974,
    longitude: 2.0833,
    airportCode: 'BCN',
    contactEmail: 'carga@aena.es',
    contactPhone: '+34 902 404 704',
    contactAddress: 'Josep Tarradellas Barcelona-El Prat Airport',
    sortOrder: 141,
  },

  // ─── Portugal ───────────────────────────────────────────────────────────────
  {
    seedKey: 'pt-lisbon',
    name: 'Lisbon',
    countryCode: 'PT',
    timezone: 'Europe/Lisbon',
    latitude: 38.7813,
    longitude: -9.1359,
    airportCode: 'LIS',
    contactEmail: 'carga@ana.pt',
    contactPhone: '+351 218 413 500',
    contactAddress: 'Humberto Delgado Airport, Lisbon',
    sortOrder: 150,
  },
  {
    seedKey: 'pt-porto',
    name: 'Porto',
    countryCode: 'PT',
    timezone: 'Europe/Lisbon',
    latitude: 41.2481,
    longitude: -8.6814,
    airportCode: 'OPO',
    contactEmail: 'carga@ana.pt',
    contactPhone: '+351 229 432 400',
    contactAddress: 'Francisco Sá Carneiro Airport, Porto',
    sortOrder: 151,
  },

  // ─── Italy ──────────────────────────────────────────────────────────────────
  {
    seedKey: 'it-rome',
    name: 'Rome',
    countryCode: 'IT',
    timezone: 'Europe/Rome',
    latitude: 41.8003,
    longitude: 12.2389,
    airportCode: 'FCO',
    contactEmail: 'cargo@adr.it',
    contactPhone: '+39 06 65951',
    contactAddress: 'Leonardo da Vinci–Fiumicino Airport, Rome',
    sortOrder: 160,
  },
  {
    seedKey: 'it-milan',
    name: 'Milan',
    countryCode: 'IT',
    timezone: 'Europe/Rome',
    latitude: 45.6306,
    longitude: 8.7281,
    airportCode: 'MXP',
    contactEmail: 'cargo@sea-aeroportimilano.it',
    contactPhone: '+39 02 232323',
    contactAddress: 'Malpensa Airport, Milan',
    sortOrder: 161,
  },
  {
    seedKey: 'it-naples',
    name: 'Naples',
    countryCode: 'IT',
    timezone: 'Europe/Rome',
    latitude: 40.886,
    longitude: 14.2908,
    airportCode: 'NAP',
    contactEmail: 'cargo@gesac.it',
    contactPhone: '+39 081 789 6111',
    contactAddress: 'Naples International Airport',
    sortOrder: 162,
  },

  // ─── Belgium ────────────────────────────────────────────────────────────────
  {
    seedKey: 'be-brussels',
    name: 'Brussels',
    countryCode: 'BE',
    timezone: 'Europe/Brussels',
    latitude: 50.901,
    longitude: 4.4856,
    airportCode: 'BRU',
    contactEmail: 'cargo@brusselsairport.be',
    contactPhone: '+32 2 753 7753',
    contactAddress: 'Brussels Airport, Leopoldlaan, 1930 Zaventem',
    sortOrder: 170,
  },

  // ─── Switzerland ────────────────────────────────────────────────────────────
  {
    seedKey: 'ch-zurich',
    name: 'Zurich',
    countryCode: 'CH',
    timezone: 'Europe/Zurich',
    latitude: 47.4647,
    longitude: 8.5492,
    airportCode: 'ZRH',
    contactEmail: 'cargo@zurich-airport.com',
    contactPhone: '+41 43 816 2211',
    contactAddress: 'Zurich Airport, 8058 Zürich-Flughafen',
    sortOrder: 180,
  },
  {
    seedKey: 'ch-geneva',
    name: 'Geneva',
    countryCode: 'CH',
    timezone: 'Europe/Zurich',
    latitude: 46.2381,
    longitude: 6.109,
    airportCode: 'GVA',
    contactEmail: 'cargo@gva.ch',
    contactPhone: '+41 22 717 7111',
    contactAddress: 'Geneva Airport, Route de l\'Aéroport 21',
    sortOrder: 181,
  },
];
