/** Mirror of server gateway events for typed RPC */
export const WsEvents = {
  AUTH_REGISTER: "auth:register",
  AUTH_LOGIN: "auth:login",
  USERS_ME_GET: "users:me:get",
  USERS_ME_UPDATE: "users:me:update",
  JOURNEYS_CREATE: "journeys:create",
  JOURNEYS_SEARCH: "journeys:search",
  JOURNEYS_GET: "journeys:get",
  JOURNEYS_LIST_MINE: "journeys:list-mine",
  JOURNEYS_UPDATE_TRAVEL: "journeys:travel:update",
  JOURNEYS_CANCEL: "journeys:cancel",
  DELIVERY_CATEGORIES: "delivery:categories",
  DELIVERY_REQUESTS_CREATE: "delivery:requests:create",
  DELIVERY_REQUESTS_LIST: "delivery:requests:list",
  DELIVERY_REQUESTS_GET: "delivery:requests:get",
  DELIVERY_REQUESTS_TRANSITION: "delivery:requests:transition",
  NOTIFICATIONS_LIST: "notifications:list",
  NOTIFICATIONS_READ: "notifications:read",
  NOTIFICATIONS_UNREAD: "notifications:unread",
  NOTIFICATIONS_READ_ALL: "notifications:read-all",
  NOTIFICATIONS_UNREAD_COUNT: "notifications:unread-count",
  VERIFICATION_GET: "verification:get",
  VERIFICATION_SUBMIT: "verification:submit",
  REFERENCE_COUNTRIES: "reference:countries",
  REFERENCE_CITIES: "reference:cities",
  JOURNEYS_BROWSE: "journeys:browse",
  FILES_UPLOAD_URL: "files:upload-url",
  FILES_CONFIRM: "files:confirm",
  FILES_DOWNLOAD_URL: "files:download-url",
  FILES_DELETE: "files:delete",
  ADMIN_VERIFICATIONS_LIST: "admin:verifications:list",
  ADMIN_VERIFICATIONS_GET: "admin:verifications:get",
  ADMIN_VERIFICATIONS_APPROVE: "admin:verifications:approve",
  ADMIN_VERIFICATIONS_REJECT: "admin:verifications:reject",
  ADMIN_CITIES_LIST: "admin:cities:list",
  ADMIN_CITIES_GET: "admin:cities:get",
  ADMIN_CITIES_CREATE: "admin:cities:create",
  ADMIN_CITIES_UPDATE: "admin:cities:update",
  ADMIN_CITIES_DELETE: "admin:cities:delete",
  ADMIN_USERS_LIST: "admin:users:list",
  ADMIN_USERS_GET: "admin:users:get",
  ADMIN_USERS_CREATE: "admin:users:create",
  ADMIN_USERS_UPDATE: "admin:users:update",
  ADMIN_USERS_DELETE: "admin:users:delete",
  ROOM_JOIN: "room:join",
} as const;

export const PushEvents = {
  CONNECTED: "connected",
  NOTIFICATION_NEW: "notification:new",
  DELIVERY_STATUS_CHANGED: "delivery:status-changed",
  DELIVERY_REQUEST_CREATED: "delivery:request-created",
  JOURNEY_UPDATED: "journey:updated",
  USER_UPDATED: "user:updated",
  VERIFICATION_UPDATED: "verification:updated",
  RPC_RESULT: "rpc:result",
  RPC_ERROR: "rpc:error",
} as const;

export type WsEvent = (typeof WsEvents)[keyof typeof WsEvents];
